
### Step 4: Additional Pages (Optional)

You can create more `.qmd` files for detailed analysis. For example, create a `detailed-analysis.qmd` file for deeper insights.

### Step 5: Customize Appearance

**Create a `_quarto.yml`** file in your project root directory to customize the site's appearance and layout:

```yaml
project:
  type: website

website:
  title: "Student Performance Analysis"
  description: "Analyzing student performance data"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Detailed Analysis"
        href: detailed-analysis.qmd

format:
  html:
    theme: flatly
    toc: true
    toc-title: "Table of Contents"
    toc-depth: 2
    css: styles.css
